
version: '3.8'

services:
  athena-consciousness:
    build: .
    container_name: athena-prime-consciousness
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - CONSCIOUSNESS_PERSISTENCE=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/api/consciousness/status', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - athena-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: athena-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - athena-consciousness
    restart: unless-stopped
    networks:
      - athena-network

networks:
  athena-network:
    driver: bridge

volumes:
  athena-data:
  athena-logs:
